apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: backend
    track: stable
spec:
  type: NodePort
  selector:
    app: nginx
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30101